### ISSUE TITLE
Bad scoping of pgpPassphrase

### ISSUE THREAD

**Issue by jvican** [sbt/sbt-pgp#111]
`pgpPassphase` is aliased to `pgpPassphrase in Global` in `autoImport`.
  
The issue is that it is however scoped in the build. From the original code in PgpPlugin:
```
  override val buildSettings = PgpSettings.globalSettings
```
  
Therefore, if someone wants to scope `pgpPassphrase` in their global settings (via a plugin), it will be overriden by `buildSettings`. I see two ways of fixing this:
  
1. Do `override val globalSettings = PgpSettings.globalSettings`.
2. Rename the alias `pgpPassphrase` to `pgpPassphrase in ThisBuild`.

**Comment by TomLous** [comment]
Could this be the reason that when running [sbt-sonatype](https://github.com/xerial/sbt-sonatype) 's `sbt publishSigned` that it will keep prompting you for a password, even though it's definded in build.sbt? 

See my [stackoverflow](https://stackoverflow.com/questions/46021342/sbt-publishsigned-on-sonatype-nexus-via-travis-ci-with-using-pgppassphrase) question for reference.

**Comment by jvican** [comment]
The main sbt-pgp keys are referenced in the `Global` scope: https://github.com/sbt/sbt-pgp/blob/master/pgp-plugin/src/main/scala/com/typesafe/sbt/SbtPgp.scala#L24-L30. However, the keys are defined in the build scope as explained in the description of this ticket.
  
The fix to this issue would be to replace `buildSettings` by `globalSettings` in this line: https://github.com/sbt/sbt-pgp/blob/master/pgp-plugin/src/main/scala/com/typesafe/sbt/SbtPgp.scala#L41.
