### ISSUE TITLE
Can't disable root publishing on jvm+js project

### ISSUE THREAD

**Issue by loicdescotte** [sbt/sbt-pgp#116]
I can't disable root publishing on jvm+js project

## steps

`sbt publishSigned`

## problem

Error : `java.lang.RuntimeException: Repository for publishing is not specified.`

## expectation

Sbt should not try to publish root as it is set as `publishArtifact := false`

## notes

sbt version: 1.0
Link to build.sbt : https://github.com/scala-hamsters/hamsters/blob/sbt_1_0/build.sbt

**Comment by raquo** [comment]
The new way to do this seems to be `skip in publish := true`. See https://github.com/sbt/sbt/issues/3136
