### ISSUE TITLE
http://scala-sbt.org/sbt-pgp redirect to https://www.scala-sbt.org/

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-pgp#120]
![screen shot 2018-02-13 at 9 51 46](https://user-images.githubusercontent.com/389787/36128050-9ccebd52-10a3-11e8-824c-54bd3abb61c1.png)

**Comment by eed3si9n** [comment]
Thanks for the report.

**Comment by eed3si9n** [comment]
This was fixed by @JustinPihony
