### ISSUE TITLE
secret key ring doesn't start with secret key tag

### ISSUE THREAD

**Issue by ChoiByungWook** [sbt/sbt-pgp#123]
Hello,

I am running into this error whenever I attempt to use publishSigned.

(*:signedArtifacts) java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff

The weird thing is that this error is random. For example, whenever I run sbt package before running publishSigned, I run into this error.

Reference: https://github.com/xerial/sbt-sonatype/issues/67

**Comment by Synesso** [comment]
I got this error when I imported keys with gpg installed from brew, as per [this guide](https://alexn.org/blog/2017/08/16/automatic-releases-sbt-travis.html). 

Ignoring that guide and recreating the keys with `sbt pgp-cmd gen-key` resolved the problem.

**Comment by saifjsl** [comment]
Hi, not sure if this is your case. I am running this with my custom location for keyrings.

It turns out I had some files here which I deleted:
```
little-spec> show */*:pgpSecretRing
[info] ... <- delete this file
little-spec> show */*:pgpPublicRing
[info] ... <- delete this file
```
followed here: https://github.com/sbt/sbt-pgp/issues/55

**Comment by eed3si9n** [comment]
Switched using locally installed `gpg` so this should be resolved hopefully.
