### ISSUE TITLE
Wrong public key id

### ISSUE THREAD

**Issue by a-nigredo** [sbt/sbt-pgp#128]
Hi all, I have generated pgp key but during release via sbt-release plugin I have an error
``No public key: Key with id: (2dc9a9929637e20f) was not able to be located on`` because I don't have a key with 2dc9a9929637e20f. I tried to add path to custom pgp keys as document says but it did help.
Are there any explanation how to set pgp id correctly?

**Comment by eed3si9n** [comment]
Please see https://central.sonatype.org/pages/working-with-pgp-signatures.html
