### ISSUE TITLE
v1.1.2 not published for sbt 0.13.x

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-pgp#144]
[v1.1.2](https://github.com/sbt/sbt-pgp/releases/tag/v1.1.2) wasn't published for sbt 0.13: http://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.10/sbt_0.13/
Only for sbt 1.x:
http://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/

**Comment by mkurz** [comment]
Pinging @eed3si9n

**Comment by eed3si9n** [comment]
Done https://github.com/sbt/sbt-pgp/releases/tag/v1.1.2-1
