### ISSUE TITLE
When PGP_PASSPHRASE environment variable is set we should also set --pinentry-mode = loopback

### ISSUE THREAD

**Issue by davideicardi** [sbt/sbt-pgp#178]
## steps

sbt-pgp version: 2.0.1
sbt version: 1.3.13

I use sbt-pgp inside a CI with Github actions and I have configured PGP_PASSPHRASE.
Then I run `publishSigned` task.

## problem

I get the error `gpg: signing failed: Inappropriate ioctl for device"`.
This happen only on the CI, on my localhost it works correctly.

## expectation

According to https://issues.apache.org/jira/browse/MGPG-59 when executing gpg from unattended environment we should set 
`--pinentry-mode = loopback`. I'm right?
Looking at the code I see that this argument is set but only if we use `useGpgPinentry := true`. If I set this setting my action works correctly.

But I expect that everytime we set `PGP_PASSPHRASE` we should also set `--pinentry-mode = loopback`.
Also because according to the documentation `useGpgPinentry` should be used when using smart card, that it is not my case.

I'm missing something?

## notes

Here my project https://github.com/davideicardi/kaa/tree/93d86cc49de1ae28877b2bb539830f5b10b6e7fd
where you can check all the configurations.

thanks

**Comment by eed3si9n** [comment]
It might depend on the GnuPG version. As someone commented on the JIRA ticket https://issues.apache.org/jira/browse/MGPG-59 said:

> I'd like to suggest the need for a more in-depth fix for this. The problem is that there's a wide range of GnuPG versions still in use out there. For example, Ubuntu 16.04 (still LTS) has GnuPG 1.4 while Ubuntu 18.04 (also still LTS) and Homebrew (macOS) have GnuPG 2.2. As a result, a developer working on a Mac whose project uses Travis CI for builds is kind of hosed.
...
> The Maven GPG Plugin should detect the GnuPG version before invoking it for signing purposes, and it should pass the `--pinentry-mode loopback` arguments automatically (without any necessary configuration) if the GnuPG version is >= 2.1.

If not auto detection, it might be good to document the utility of `useGpgPinentry := true` under Automating PIN entry (passphrase Entry) header as well.

**Comment by davideicardi** [comment]
Maybe sbt-pgp should adapt to the latest version behavior and document about other versions requirements?

There isn any drawback to set `--pinentry-mode = loopback` an every unattended executions, also with older versions?

**Comment by eed3si9n** [comment]
> There isn any drawback to set `--pinentry-mode = loopback` an every unattended executions, also with older versions?

This could be something easy to test with Travis CI. If we copy the directory https://github.com/sbt/sbt-pgp/tree/master/sbt-pgp/src/sbt-test/sbt-pgp/credentials and add `useGpgPinentry := true` that might indicate that GnuPG 1.4 is ok with the option.

**Comment by davideicardi** [comment]
I have created a PR, https://github.com/sbt/sbt-pgp/pull/179, with your suggestion. But it doesn't compile on travis:
```
[info] Error during sbt execution: Error retrieving required libraries
[info]   (see /tmp/sbt_e154ffa1/pinentry-loopback-test/global/boot/update.log for complete log)
[info] Error: Could not retrieve sbt 0.13.16
```

Maybe I have missed some config?

**Comment by eed3si9n** [comment]
Maybe there was some network error initially. After restarting the job, I'm seeing the following error:

```
[info] [error] gpg: Invalid option "--pinentry-mode"
[info] java.lang.RuntimeException: Failure running 'gpg --no-default-keyring --keyring /tmp/sbt_52984d8f/pinentry-loopback-test/pubring.pgp --pinentry-mode loopback --detach-sign --armor --use-agent --output /tmp/sbt_52984d8f/pinentry-loopback-test/target/scala-2.13/test_2.13-1.0.pom.asc /tmp/sbt_52984d8f/pinentry-loopback-test/target/scala-2.13/test_2.13-1.0.pom'.  Exit code: 2
[info] 	at scala.sys.package$.error(package.scala:27)
[info] 	at com.jsuereth.sbtpgp.CommandLineGpgPinentrySigner.sign(PgpSigner.scala:92)
...
```

**Comment by davideicardi** [comment]
Thanks @eed3si9n. So the only solution is to detect the version and change the code accordling. I'm closing this issue for now. If I have time in the future I can try to implement this.

**Comment by eed3si9n** [comment]
I fixed this in https://github.com/sbt/sbt-pgp/pull/184
