### ISSUE TITLE
"gpg: invalid option "--pinentry-mode"" when gpg is 2.0

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-pgp#191]
## steps

```console
gpg --version
gpg (GnuPG) 2.0.22
```

## problem

```
[info] gpg: invalid option "--pinentry-mode"
--
  | [error] java.lang.RuntimeException: Failure running 'gpg --batch --pinentry-mode loopback --passphrase *** --detach-sign --armor --use-agent --output /var/lib/buildkite-agent/builds/...'.  Exit code: 2
```

## notes

Unfortunately the `--pinentry-mode` option is only available from GPG version 2.1, but `isLegacyGpg` just checks the major version. When the plugin is used with 2.0.x we get an `invalid option` error.

See [here](https://github.com/jvalecillos/vscode-gpg/issues/14) for a similar issue.

_Originally posted by @aakoshh in https://github.com/sbt/sbt-pgp/issues/184#issuecomment-802931904_

**Comment by winitzki** [comment]
To fix: https://github.com/sbt/sbt-pgp/pull/197
