### ISSUE TITLE
How to switch to a different keyserver?

### ISSUE THREAD

**Issue by davideicardi** [sbt/sbt-pgp#192]
This is not a problem of sbt-pgp, but given that `https://sks-keyservers.net/ ` seems to be down right now (invalid certificate), I try to understand how to switch to another key server, but I don't find any information on how to change the default keyserver used by sbt-pgp.

Should I change `~/.gnupg/gpg.conf` adding `keyserver keyserver.ubuntu.com`?

**Comment by eed3si9n** [comment]
Are you running into an issue while running `checkPgpSignatures`? If so could you paste the full error message here for later reference?

**Comment by davideicardi** [comment]
Sorry, probably I made some false assumptions.
I had a github action workflow that publish to sonatype, using sbt-sonatype plugin, with `sbt publishSigned`.
It always worked, but today I received an error like:
```
Failed: signature-staging, failureMessage:No public key: Key with id: (...) was not able to be located on <a href="http://pool.sks-keyservers.net:11371/">http://pool.sks-keyservers.net:11371/</a>. Upload your public key and try the operation again.
```

Now given that when publishing my key to `http://pool.sks-keyservers.net` using:
```
> gpg --keyserver hkps://pool.sks-keyservers.net:11371 --recv-keys 374DCA2C0632C103E5F29655558458A68E2E452B
```
I received:
```
gpg: keyserver receive failed: No name
```
And given that the server seems to be not working due to certificate issue I assumed it was a problem related to the server used by sbt-pgp. But not so sure now ;-) ...

Now the github action seems to work again, without changing nothing. So not sure what was the problem, I think something server side but ...

Anyway I'm closing the issue, because cannot reproduce it. Sorry ...

**Comment by davideicardi** [comment]
Just for reference: https://github.com/SKS-Keyserver/sks-keyserver/issues/87

It seems that sks-keyserver will be discontinued.
