### ISSUE TITLE
gpg: signing failed: File exists

### ISSUE THREAD

**Issue by Haaroon** [sbt/sbt-pgp#199]
## steps

sbt-pgp version: 1.1.0
sbt version: 1.7.0

## problem

I run 

> sbt release

i get 

>  [error] java.lang.RuntimeException: Failure running 'gpg --batch --pinentry-mode loopback --passphrase xxxxxxxx --detach-sign --armor --use-agent --output /Users/xxx/Documents/dev/Raphtory/target/scala-2.13/raphtory_2.13-0.2.1.pom.asc /Users/xxx/Documents/dev/Raphtory/target/scala-2.13/raphtory_2.13-0.2.1.pom'.  Exit code: 2

For some reason the .asc file is being created twice and causes PGP to fail signing

This can be fixed if u add a `--yes` to the gpg command, but you cannot do this in the automated non-interactive build.
How can I solve this? 

## expectation

it should not error, if we add the `--yes` flag

**Comment by eed3si9n** [comment]
@Haaroon Thanks for the report. Do you know the version of GnuPG available on your system?

**Comment by Haaroon** [comment]
@eed3si9n 

```
gpg (GnuPG) 2.3.8
libgcrypt 1.10.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/haaroony/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by Haaroon** [comment]
Another issue, if i use this with the `sbt-release` eventually the release gets stuck and expecting the user to `Enter new filename:` which makes this interactive rather than non-interactive.

**Comment by eed3si9n** [comment]
See https://github.com/sbt/sbt-ci-release for fully automated release. For sbt-pgp portion, we use environment variable to pass in the creds.

**Comment by Haaroon** [comment]
Okay I have found a workaround. You create a ~/.gpg/gpg.conf and inside write `yes` this will default any command

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt-pgp/pull/200

**Comment by Haaroon** [comment]
Thanks this looks great. ﻿
Here's my PR for this - #200
