### ISSUE TITLE
Exclude project from being published

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt-pgp#42]
I can't find any information on how to exclude a particular sub project in a multi project from being published via `publish-signed`.

If I have an aggregate `root` and two aggregates sub projects `foo` and `bar`, how do I make sbt-pgp skip `root` and not publish that? It would also be useful to add that information to the documentation website. Thanks.

**Comment by seanparsons** [comment]
This doesn't work at all for me and it would appear 1.0.0 doesn't honour the publishArtifact setting.

**Comment by xeno-by** [comment]
I second this.
