### ISSUE TITLE
Select used gpg key

### ISSUE THREAD

**Issue by cvogt** [sbt/sbt-pgp#47]
I failed selecting a desired key for signing using pgpSigningKey or usePgpKeyHex. I always end up with `[error] (.../*:signedArtifacts) Could not find public key: ...`. None of the numeric or hex key ids listed for my secret key in gpg --list-keys or gpg --list-keys --with-colon seem to work.

@jsuereth suggested some fuzzy matching on the key id may fix that, hence the ticket.

**Comment by metasim** [comment]
+1. Had to resort to `useGpg` to get my release to work. The bouncycastle implementation was selecting the wrong key, and couldn't figure out how to change it.

**Comment by NicolasRouquette** [comment]
I experienced the same problem, the BountyCastle library only loads the first key in the ring; even if there are several.

As a workaround to use BCP, I created *.gpg files with only 1 key; the one that I intend to use.

FYI: BCP is the only way to use the pgp passphrase. With the GPG command line configuration, the passphrase must come from a GPG agent since sbt-pgp doesn't use the "--batch --passphrase-fd 0" option of GPG.

**Comment by jvican** [comment]
@NicolasRouquette Thanks for the workaround. +1 to this feature. I may even give it a try soon.

**Comment by NicolasRouquette** [comment]
@jvican You're welcome. I use this trick for all my open source projects I build on Travis-CI:
https://travis-ci.org/JPL-IMCE
https://travis-ci.org/TIWG

**Comment by djspiewak** [comment]
Just as a side note, this is still current.  Bit me just now.

**Comment by johnynek** [comment]
creating files with single keys, like here:

https://alexn.org/blog/2017/08/16/automatic-releases-sbt-travis.html

let me work around this bug.

**Comment by djspiewak** [comment]
@johnynek Unless I’m missing something, Alex is still creating a paired public/private master key. That doesn’t really address the most important use case here, which is key splitting.

**Comment by johnynek** [comment]
It addressed my case, which was having a work key I shouldn't use for this as well as wanting something to sign for publishing. I just created a separate public/secret keyring with a new key and pointed sbt-pgp at that.

**Comment by eed3si9n** [comment]
useGpg is now default.
