### ISSUE TITLE
Failed to run pgp-cmd: GeneratePgpKey()

### ISSUE THREAD

**Issue by EECOLOR** [sbt/sbt-pgp#55]
Sbt version: 0.13.5
sbt-pgp version: 0.8.3

Steps to reproduce:
- Added `addSbtPlugin("com.typesafe.sbt" % "sbt-pgp" % "0.8.3")` to `project/plugins.sbt`.
- Started `sbt` prompt in the root of the project
- Ran the `pgp-cmd gen-key` command
- Got "Cannot modify keyrings when in read-only mode.  Run `set pgpReadOnly := false` before running this command."
- Ran `set pgpReadOnly := false`
- Ran `pgp-cmd gen-key`
- Got "Failed to run pgp-cmd: GeneratePgpKey().   Please report this issue at http://github.com/sbt/sbt-pgp/issues"

**Comment by malcolmgreaves** [comment]
This solved the same problem I had. Thanks for posting!

**Comment by mig-foxbat** [comment]
Thanks @EECOLOR  worked for me as well..
