### ISSUE TITLE
Can't launch sbt because of ".sbt/0.13/plugins/gpg.sbt:3: error: not found: value pgpSecretRing" error

### ISSUE THREAD

**Issue by azakordonets** [sbt/sbt-pgp#69]
I have pgpSecretRing and phpPubRing already generated by PGP UI tool. I have created ```~/.sbt/0.13/plugins/pgp.sbt``` file and have put there next content : 

```scala
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")

pgpSecretRing := file("/Users/biercoff/.gnupg/secring.gpg")

pgpPublicRing := file("/Users/biercoff/.gnupg/pubring.gpg")
```

When i try to run sbt in my project, i get next error : 

```bash 
➜  fabricator git:(master) sbt
/Users/biercoff/.sbt/0.13/plugins/gpg.sbt:3: error: not found: value pgpSecretRing
pgpSecretRing := file("/Users/biercoff/.gnupg/secring.gpg")
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

What am i missing ?

**Comment by utgarda** [comment]
As far as I understood the docs, those settings should go to ~/.sbt/gpg.sbt, not the file where you add the plugin. Doesn't seem to work for me, though.

**Comment by jsuereth** [comment]
you need to split your settings:

`~/.sbt/0.13/plugins/pgp.sbt` - This configures the inclusion of the plugin

```scala
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
```

`~/.sbt/0.13/pgp.sbt` - This configures default settings for builds.

```scala
pgpSecretRing := file("/Users/biercoff/.gnupg/secring.gpg")
pgpPublicRing := file("/Users/biercoff/.gnupg/pubring.gpg")
```

Hope that helps!

**Comment by mrmechko** [comment]
In a similar vein, my `~/.sbt/pgp.sbt` file is essentially identical to the one above, but I'm still getting the same error. Is this because `addSbtPlugin(...)` is in a project specific file?  I suppose the question is are the global `.sbt` files loaded before the project specific ones?

**Comment by tel** [comment]
@mrmechko Just discovered this myself today: you need to fully qualify your keys in `pgp.sbt`, e.g.

```
com.typesafe.sbt.pgp.PgpKeys.pgpSecretRing := file("/Users/tel/.gnupgp/secring.asc")
com.typesafe.sbt.pgp.PgpKeys.pgpPublicRing := file("/Users/tel/.gnupgp/pubring.asc")
```

**Comment by dwickern** [comment]
For the changes to stick, I also had to specify `in Global`:
```
// ~/.sbt/0.13/pgp.sbt
com.typesafe.sbt.pgp.PgpKeys.pgpSecretRing in Global := file(".../secring.asc")
com.typesafe.sbt.pgp.PgpKeys.pgpPublicRing in Global := file(".../pubring.asc")
```

To verify, you can run `show */*:pgpSecretRing`

**Comment by BenWhitehead** [comment]
If you want to use `usePgpKeyHex` for a specific key add (when using sbt-pgp 1.0.0)
```scala
com.typesafe.sbt.SbtPgp.autoImportImpl.usePgpKeyHex("<hexid>")
```

**Comment by johnynek** [comment]
with 1.0.0 I had to use 

`com.typesafe.sbt.SbtPgp.autoImportImpl.pgpSecretRing := ` to get things to work.
