### ISSUE TITLE
GPG 2.1+ doesn't use secret keyring anymore

### ISSUE THREAD

**Issue by utgarda** [sbt/sbt-pgp#72]
And my gpg is 2.1, so I can't use it with sbt-pgp.

https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration.html

it says:

> ~/.gnupg/secring.gpg
>        A secret keyring as used by GnuPG versions before 2.1. It is not used by GnuPG 2.1 and later. 

Indeed, I don't have any secret ring file: 

```
$ ls ~/.gnupg/
crls.d/  openpgp-revocs.d/  private-keys-v1.d/  
gpg.conf  pubring.kbx  sshcontrol  trustdb.gpg
```

Would be nice to have the new versions of gpg supported.

**Comment by jsuereth** [comment]
IS it called 'trustdb.gpg' now?  Do you know if bouncy castle supports these rings?

**Comment by alexduf** [comment]
@jsuereth I'm afraid the trustdb.gpg doesn't do the trick.
@utgarda any workaround aside from downgrading?

**Comment by utgarda** [comment]
@alexduf sorry, I found none. Forgot the whole thing already. I did it manually that time.

**Comment by alexduf** [comment]
@utgarda thanks, I had to downgrade to workaround the issue.

**Comment by Lasering** [comment]
From what I could gather from the [GnuPG 2.1 documentation](https://gnupg.org/faq/whats-new-in-2.1.html#nosecring) `trustdb.gpg` is NOT the new `secring.pgp`. The "new" file is actually a directory `private-keys-v1.d`.

**Comment by lunaryorn** [comment]
gpg2.1 expects all private keys to be accessed via gpg-agent, so I don't think that BouncyCastle is up to the task yet.

I got the native implementation to work though, e.g.

```scala
> set PgpKeys.useGpg in Global := true
[info] Defining */*:useGpg
[info] The new value will be used by */*:pgpSigner, */*:pgpVerifier
[info] Reapplying settings...
[info] Set current project to play-json-refined (in build file:…)
> set PgpKeys.gpgCommand in Global := "gpg2"
[info] Defining */*:gpgCommand
[info] The new value will be used by */*:pgpSigner, */*:pgpVerifier
[info] Reapplying settings...
[info] Set current project to play-json-refined (in build file:…)
> publish-local-signed
[…]
[success] Total time: 2 s, completed 04.01.2017 16:30:43
```

I added the plugin to my global SBT configuration, created `~/.sbt/0.13/gpg.sbt` with the following contents, and can now happily sign my releases with gpg2.1 😎 

```
PgpKeys.useGpg in Global := true
PgpKeys.gpgCommand in Global := "gpg2"
```

**Comment by rtyley** [comment]
There's a corresponding issue for Gradle: https://github.com/gradle/gradle/issues/888 - note there's a workaround given there by @huxi to execute:

```
gpg --export-secret-keys >~/.gnupg/secring.gpg
```

...which produces the old-format file which both Gradle's signing plugin and sbt-pgp can read.

Adding Bouncy Castle support for the new `private-keys-v1.d` format was acknowledged as an issue by @cwgit a few weeks ago: http://bouncy-castle.1462172.n4.nabble.com/GnuPG-2-1-New-file-formats-tp4658595p4658596.html

**Comment by jvican** [comment]
@rtyley Thanks for sharing.
  
Hope someone tackles this one soon! I find it important with the advent of the new key format.

**Comment by drxcc** [comment]
Note: my problem was resolved with with @djspiewak suggestion in https://github.com/djspiewak/sbt-spiewak/commit/3cd2e6db22ab94e6e05f82a1af65d317d3b0745f to use:

```
pgpSecretRing := pgpPublicRing.value
```

which is a separate issue sbt/sbt-pgp#126
