### ISSUE TITLE
problem with pgp-cmd list-keys

### ISSUE THREAD

**Issue by mdread** [sbt/sbt-pgp#82]
when i run `pgp-cmd list-keys` it fails with the following message:

`Failed to run pgp-cmd: ListKeys().   Please report this issue at http://github.com/sbt/sbt-pgp/issues`

any idea what can it be?
i read on another issue (#55) that deleting secring.asc and pubring.asc solves the problem with gen-key, not sure if it can help here, but i need to use the keys i already have

**Comment by AnirudhVyas** [comment]
I have a similar problem when trying to send the key.

```scala
> pgp-cmd send-key keyname hkp://pool.sks-keyservers.net
Failed to run pgp-cmd: SendKey(keyname,hkp://pool.sks-keyservers.net).   Please report this issue at http://github.com/sbt/sbt-pgp/issues
> 
````

**Comment by AnirudhVyas** [comment]
OK I take this comment back - did you try 
```scala
show */*:pgpPublicRing
```
? I rm -rvf'd and recreated the keys again and it worked ... the list key also works - I am using 0.13.8 version for SBT.

**Comment by blast-hardcheese** [comment]
As of 1.1.1, I was able to resolve this issue by:
```
mkdir -p ~/.sbt/gpg/
gpg2 --export-secret-keys --armor > ~/.sbt/gpg/secring.asc
gpg2 --export --armor > ~/.sbt/gpg/pubring.asc
```
as I couldn't convince sbt-pgp to import my keys from gpg2.

**Comment by eed3si9n** [comment]
Removing pgp-cmd feature.
