### ISSUE TITLE
doc recommends 1.0.0 but it isn't on bintray?

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-pgp#83]
at http://www.scala-sbt.org/sbt-pgp/ recommends 1.0.0 but at https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-pgp/scala_2.10/sbt_0.13/ there are no 1.0.0 artifacts

**Comment by timcharper** [comment]
`sbt-pgp` should download from here:

https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.10/sbt_0.13/1.0.0/jars/sbt-pgp.jar

I recommend that this issue be closed.
