### ISSUE TITLE
Empty files in `~/.gnupg/{pubring,secring}.gpg` causes `sbt-pgp` to fail, even if configured to load keys elsewhere

### ISSUE THREAD

**Issue by timcharper** [sbt/sbt-pgp#86]
As seen in the gitter chat room:

:point_up: [February 2, 2016 4:59 PM](https://gitter.im/sbt/sbt?at=56b142d1c54bc2bf180da3d1)

Strangely, even though I had configured `sbt-pgp` to load from a different location (by specifying the `pgpSecretRing` and `pgpPublicRing` settings), trying to use `sbt-pgp` `1.0.0` to publish an artifact would fail with the following error:

```
[trace] Stack trace suppressed: run last *:signedArtifacts for the full output.
[error] (*:signedArtifacts) java.io.IOException: secret key ring doesn't start with secret key tag: tag 0xffffffff
[error] Total time: 5 s, completed Feb 2, 2016 3:39:47 PM
```

Removing the empty files from `~/.gnupg/` fixed the issue; I don't know how they were created in the first place, and I've never stored them there so was really confused by the error message.

Two things would've helped:
- `sbt-pgp` should not be looking at `~/.gnupg/{pubring,secring}.gpg` if configured to look elsewhere via `pgpSecretRing` and `pgpPublicRing`.
- `sbt-pgp` should output the path of the file which failed to load. For example:
  
  ```
  [error] (*:signedArtifacts) java.io.IOException: secret key ring in ~/.gnupg/secring.gpg doesn't start with secret key tag: tag 0xffffffff
  ```

**Comment by jsuereth** [comment]
Thanks for the report!  Will look into it.

**Comment by akozhemiakin** [comment]
Some similar thing happened with me, but I did not touch any settings.
I got the following:
```
(*:signedArtifacts) java.io.IOException: secret key ring doesn't start with secret 
```
Removing files from ~/.gnupg helped me.

**Comment by timcharper** [comment]
That's so weird!!! I wonder where they're coming from??? Maybe the java lib on which sbt-pgp depends?

**Comment by jsuereth** [comment]
krap, I think I may understand this now. I think it's coming from *one* of the meta-builds, which is practically impossible to write a test for (you have to use the released plugin).   Can you guys let me know what your setup looks like?

**Comment by timcharper** [comment]
Sure! I'm not having the problem anymore, and don't know how to get it back in to that state. But...

```
~ $ cat ~/.sbt/0.13/gpg.sbt
import com.typesafe.sbt.pgp.PgpKeys.{pgpPassphrase, pgpSecretRing, pgpPublicRing, useGpg, gpgCommand}
// import com.jsuereth.sbt.pgp.PgpKeys.{pgpPassphrase, pgpSecretRing, pgpPublicRing}

useGpg := true

// gpgCommand := "/usr/local/bin/gpg"

(pgpPassphrase in Global) := Some("<redacted>".toCharArray)

pgpSecretRing := file("/Users/timcharper/.sbt/gpg/secring.asc")

pgpPublicRing := file("/Users/timcharper/.sbt/gpg/pubring.asc")
```

**Comment by soc** [comment]
I think I have the same issue, except that it fails with `Wrong passphrase. aborting...` regardless of what I do. Renaming `.gnupg` seems to make it work.
I don't the point of being able to set `pgpSecretRing` or `pgpPublicRing` in the first place, if it breaks _everything_,

**Comment by eed3si9n** [comment]
Added a new key for `gpg` - https://github.com/sbt/sbt-pgp/pull/166
