### ISSUE TITLE
Exception thrown in command `pgp-cmd gen-key` is swallowed

### ISSUE THREAD

**Issue by timcharper** [sbt/sbt-pgp#87]
The exception is being swallowed when running `pgp-cmd gen-key`. I don't know if it's sbt's fault.

Here's the output:

```
> pgp-cmd gen-key
Failed to run pgp-cmd: GeneratePgpKey().   Please report this issue at http://github.com/sbt/sbt-pgp/issues
>
```

I dug into the source, built and deployed my own jar for sbt-pgp, and found that it was throwing this exception:

`Public key ring (/Users/timcharper/.gnupg/pubring.gpg) already exists!`

I've narrowed it down and I've confirmed that the exception is being dropped somewhere inside of the [call to EvaluateTask.runTask](https://github.com/sbt/sbt-pgp/blob/73be280943088f2ddf0e33a471b0dfec1cf4a6db/pgp-plugin/src/main/scala/com/typesafe/sbt/pgp/PgpSettings.scala#L57)

**Comment by jsuereth** [comment]
sbt does this I believe.   It could be the way we catch/log exception in the pgp-cmd needs to be improved.

**Comment by soc** [comment]
It also seems to complain when `pgpSecretRing` and `pgpPublicRing` are set to a different directory which is pretty pointless.

**Comment by eed3si9n** [comment]
Killed pgp-cmd in https://github.com/sbt/sbt-pgp/pull/164.
