### ISSUE TITLE
pgpPassphrase is ignored and the plugin prompts for input regardless

### ISSUE THREAD

**Issue by alexflav23** [sbt/sbt-pgp#96]
Hi @jsuereth,

Trying to publish from inside Travis CI using encrypted variables and so on, the problem is the following doesn't seem to do much. Everything seems to be correct setup wise, and travis is doing the right thing, but the PGP plugin is ignoring the `pgpPassphrase` completely, even if its set.

```scala

lazy val pgpPass = Option(System.getenv("pgp_pass"))

pgpPassphrase := {
    if (RunningUnderCi && pgpPass.isDefined) {
      println("Running under CI and PGP password specified under settings.")
      pgpPass.map(_.toCharArray)
    } else {
      println("Could not find settings for a PGP passphrase.")
      println(s"pgpPass defined in environemnt: ${pgpPass.isDefined}")
      println(s"Running under CI: $RunningUnderCi")
      None
    }
},
```

I can clearly see all the logging for `println("Running under CI and PGP password specified under settings.")` in the build log, but then the build halts indefinitely waiting for user input.

Is there a way around this or does this need plugin level patching?

**Comment by alexflav23** [comment]
All good, turns out issue was on the build side, the export to the environment was failing silently, because of some bizarre restrictions. This works as expected.

**Comment by TomLous** [comment]
Can you elaborate on the "bizarre restrictions"? I'm having the same issues
